CREATE DATABASE `home_model` /*!40100 DEFAULT CHARACTER SET latin1 */;

CREATE TABLE `Devices` (
  `DeviceID` varchar(15) NOT NULL,
  `DeviceName` varchar(45) NOT NULL,
  PRIMARY KEY (`DeviceID`),
  UNIQUE KEY `DeviceName_UNIQUE` (`DeviceName`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `Logs` (
  `LogID` int(11) NOT NULL AUTO_INCREMENT,
  `CreatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DeviceID` varchar(15) NOT NULL,
  `ThingID` int(11) NOT NULL,
  `ThingState` int(11) NOT NULL,
  PRIMARY KEY (`LogID`),
  KEY `LOGS_DEVICE_ID_FK_idx` (`DeviceID`),
  KEY `LOGS_THINGS_FK_idx` (`ThingID`),
  CONSTRAINT `LOGS_DEVICE_FK` FOREIGN KEY (`DeviceID`) REFERENCES `Devices` (`DeviceID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `LOGS_THINGS_FK` FOREIGN KEY (`ThingID`) REFERENCES `Things` (`ThingID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=17842 DEFAULT CHARSET=latin1;

CREATE TABLE `Things` (
  `ThingID` int(11) NOT NULL,
  `DeviceID` varchar(15) NOT NULL,
  `ThingName` varchar(45) NOT NULL,
  `ThingType` varchar(45) NOT NULL,
  PRIMARY KEY (`ThingID`,`DeviceID`),
  KEY `COMPOSITE_THINGID` (`ThingID`),
  KEY `COMPOSITE_DEVICEID` (`DeviceID`),
  CONSTRAINT `THINGS_DEVICE_FK` FOREIGN KEY (`DeviceID`) REFERENCES `Devices` (`DeviceID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `UserDevices` (
  `UserID` varchar(15) NOT NULL,
  `DeviceID` varchar(15) NOT NULL,
  PRIMARY KEY (`UserID`,`DeviceID`),
  KEY `UserID_idx` (`UserID`),
  KEY `DeviceID_idx` (`DeviceID`),
  CONSTRAINT `USERDEVICES_DEVICES_FK` FOREIGN KEY (`DeviceID`) REFERENCES `Devices` (`DeviceID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `Users` (
  `UserID` int(11) NOT NULL AUTO_INCREMENT,
  `UserName` varchar(45) NOT NULL,
  `Password` varchar(64) NOT NULL,
  `Email` varchar(128) NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE KEY `UserName_UNIQUE` (`UserName`),
  UNIQUE KEY `Email_UNIQUE` (`Email`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
